### PR TITLE
Add Love Rap cues (Attempt #2)

### PR DESCRIPTION
**Pull request by ArendAlphaEagle**
#99  Prerequisites
* [x] I have read and understood the [contribution guidelines](CONTRIBUTING.md)
* [x] This pull request follows the code style of the project
* [x] I have tested this feature thoroughly WITH THE USE of the load-all-sounds starter
  * [Link to a video of proof of testing](https://www.youtube.com/watch?v=oP6XWOf78BY)

**Issues Fixed:** The corresponding data.json file has been adjusted so the cues and patterns follow the original's as closely as I could

### Changes Proposed in this Pull Request
* Add cues and patterns from Love Rap from Rhythm Heaven Fever

...

### CODE REVIEW

**Comment by ArendAlphaEagle** [comment]
I updated the data.json file with durations that follow the original game more closely (the patterns have also been adjusted accordingly).

I really tried my best to mimic the original game, having used a Perfect version of Love Rap side by side. It proved quite difficult at times. I hope I did a good enough job.

**Comment by chrislo27** [comment]
From the video, you still are using a base BPM of 120. You should be basing all the durations/positions on Love Rap's original BPM.

**Comment by ArendAlphaEagle** [comment]
...this may be a bit embarrassing to tell, but I actually don't really know what the original BPM for Love Rap actually is.

**Comment by ArendAlphaEagle** [comment]
I'll be attempting to rework the durations and positions under a BPM of 90. I hope that's the correct BPM (if not, please tell).

**Comment by chrislo27** [comment]
I think it's 90 as well. If you need the music to test, you can use this https://raw.githubusercontent.com/chrislo27/Baristron/8b0e2c8b3802fb86cd979d4d1e6a1aec3f80af65/music/Love%20Rap.mp3

**Comment by ArendAlphaEagle** [comment]
I now updated the data.json file. Now it should play with the durations and positions set for its original BPM, which is apparently 83 if the Rhythm Heaven Wiki is to be believed. I decided to look it up there since I kept switching between 90 BPM and 80 BPM, hoping the wiki would have a better, more definite answer.

...in retrospect, I just should've done this earlier.

Nevertheless, it's updated now and I got a video uploaded [here](https://www.youtube.com/watch?v=oP6XWOf78BY), showcasing the new version.

**Pull request merged**
