### PR TITLE
Fix Marching Orders GBA's icon (FINALLY), add Spanish Big Rock Finish, and make the strum cue stretchable

### PR DESCRIPTION
**Pull request by GuardedLolz**
### Prerequisites
* [X] I have read and understood the [contribution guidelines](CONTRIBUTING.md)
* [X] This pull request follows the code style of the project
* [X] I have tested this feature thoroughly WITH THE USE of the load-all-sounds starter
capture
* [X] This pull request is merging into **`dev`**

### Changes Proposed in this Pull Request
Stated in the name

...

### CODE REVIEW

**Comment by GuardedLolz** [comment]
Look at the edges on the cue, and you'll know I'm not kidding.

**Comment by Miracle22s** [comment]
First, we need some drum cue with is important.

**Review by chrislo27 — CHANGES_REQUESTED** [review]
Missing games.json change

**Comment by GuardedLolz** [comment]
Adding the drum cues would mean we would need to find a solo guitar sound effect.

**Comment by Miracle22s** [comment]
That's correct.

**Comment by GuardedLolz** [comment]
I'm gonna go close and enhance this fork and add more stuff.

**Pull request closed without merging**
