### PR TITLE
Add support for localizing game names

### PR DESCRIPTION
**Pull request by Armodillomatt12**
### Prerequisites
* [x] I have read and understood the [contribution guidelines](CONTRIBUTING.md)
* [x] This pull request follows the code style of the project
* [x] I have tested this feature thoroughly WITH THE USE of the load-all-sounds starter
  * [Link to a video of proof of testing](https://www.youtube.com/watch?v=7o1M58OpYuA)

**Issues Fixed:** [Any issues fixed by this pull request]

### Changes Proposed in this Pull Request
* Add the cues from Animal Acrobat from Rhythm Heaven Megamix

...

### CODE REVIEW

**Comment by chrislo27** [comment]
Why did you base your branch off `localizable-game-names`? That branch is stale and has merge conflicts.

**Comment by Armodillomatt12** [comment]
i didn't know where to find the file called Animal Acrobat.

**Comment by GuardedLolz** [comment]
Also, it needs to be all lowercase, as is the standard naming style of the project. Furthermore, it seems you based your Animal Acrobat off of mine.

**Comment by Armodillomatt12** [comment]
that's because it is yours. i just don't what to do. everything i do just results of me getting scold by either @chrislo27 or someone else. it seems like no one needs my help. why even bother with this... no one understands me. i just want to help but it ends up that i'm making everything worst.

**Comment by GuardedLolz** [comment]
You can help. You just need to try harder and understand GitHub better.

**Comment by Armodillomatt12** [comment]
ok. i mean. i got the audio and the data.json so that's a start, right? @GuardedLolz

**Comment by GuardedLolz** [comment]
Yeah.

**Comment by Armodillomatt12** [comment]
@GuardedLolz ok

**Pull request closed without merging**
