### PR TITLE
correcting turbo rally pattern

### PR DESCRIPTION
**Pull request by Armodillomatt12**
### Prerequisites
* [x] I have read and understood the [contribution guidelines](CONTRIBUTING.md)
* [x] This pull request follows the code style of the project
* [x] I have tested this feature thoroughly WITH THE USE of the load-all-sounds starter
  * [Link to a video of proof of testing](https://www.youtube.com/watch?v=lYXIrkqs4mY)

**Issues Fixed:** finally corrected the turbo pattern in rhythm rally.

### Changes Proposed in this Pull Request
* it used to be the player passing the ball twice in turbo which it's supposed to be 4 times. i edited the `data.json` in `rhythmRally` folder to be more correct to rhythm rally 2/cosmic rhythm rally

...
P.S. IDK why the files from the pull request i did for freeze frame is there but pay more attention to the rhythm rally part

### CODE REVIEW

**Comment by chrislo27** [comment]
Rebase first. Try to use command line git instead of deleting/reforking.

**Comment by Armodillomatt12** [comment]
i can't because of my potato computer

**Comment by Armodillomatt12** [comment]
everything has to be so difficult sometimes. i tried cloning it but it fails badly. that's why i called my computer a potato

**Comment by Armodillomatt12** [comment]
i'm just gonna close this because this piece of trash is bugging me the hell out

**Pull request closed without merging**
