### PR TITLE
Add Love Rap cues

### PR DESCRIPTION
**Pull request by ArendAlphaEagle**
### Prerequisites
* [x] I have read and understood the [contribution guidelines](CONTRIBUTING.md)
* [x] This pull request follows the code style of the project
* [x] I have tested this feature thoroughly WITH THE USE of the load-all-sounds starter
  * [Link to a video of proof of testing](https://www.youtube.com/watch?v=-uU2m_pL-og)

**Issues Fixed:** [Any issues fixed by this pull request]

### Changes Proposed in this Pull Request
* Add the cues from Love Rap from Rhythm Heaven Fever

...

### CODE REVIEW

**Comment by chrislo27** [comment]
Please database it.

**Comment by ArendAlphaEagle** [comment]
Tried my best in making this data.json file. Hopefully it's good enough.

**Comment by chrislo27** [comment]
Please provide proof of testing (a video) + create an icon.

**Comment by ArendAlphaEagle** [comment]
I have updated the data.json file as I discovered some errors, and recorded a simple test video based on these changes [here](https://www.youtube.com/watch?v=-uU2m_pL-og).

Also, it seems there has already been an icon for the game created? I don't think I need to make a different one.

**Comment by ArendAlphaEagle** [comment]
...I haven't received any sort of feedback or commands since I uploaded the test video. Are the things I did good enough? Do I need to improve on something? Some feedback would be appreciated.

**Comment by chrislo27** [comment]
I wasn't checking (was super busy) and your data files should use the tempo of the original game. Love Rap is not 120 BPM. Please redo the data file.

**Pull request merged**
