### PR TITLE
Add Freeze Frame

### PR DESCRIPTION
**Pull request by Armodillomatt12**
### Prerequisites
* [x] I have read and understood the [contribution guidelines](CONTRIBUTING.md)
* [x] This pull request follows the code style of the project
* [x] I have tested this feature thoroughly WITH THE USE of the load-all-sounds starter
  * [Link to a video of proof of testing](https://www.youtube.com/watch?v=7HolFz9raQw)

**Issues Fixed:** [Any issues fixed by this pull request]

### Changes Proposed in this Pull Request
* added freeze frame to `games.json` and added cues for it as well

...

### CODE REVIEW

**Comment by GuardedLolz** [comment]
Good, but you're usually supposed to rebase your fork.

**Comment by Armodillomatt12** [comment]
@GuardedLolz oh, how do i do that?

**Comment by GuardedLolz** [comment]
Delete your fork and make a new one.

**Comment by Armodillomatt12** [comment]
@GuardedLolz ok

**Pull request closed without merging**
