### PR TITLE
Add Love Rap, add Clap cue sfx in Bon Odori

### PR DESCRIPTION
**Pull request by ArendAlphaEagle**
### Prerequisites
* [x] I have read and understood the [contribution guidelines](CONTRIBUTING.md)
* [ ] This pull request follows the code style of the project
* [ ] I have tested this feature thoroughly WITH THE USE of the load-all-sounds starter
  * [Link to a video of proof of testing]()

**Issues Fixed:** [Any issues fixed by this pull request]

### Changes Proposed in this Pull Request
* Add Love Rap from Rhythm Heaven Fever
* Add a clapping cue sound effect in Bon Odori from Rhythm Tengoku (GBA)

...

### CODE REVIEW

**Comment by chrislo27** [comment]
Rebase your branch to current master. I am not going to accept this with that many trailing commits.

**Comment by chrislo27** [comment]
Sorry, don't rebase. Don't rebase into localizable-game-names, go into master.

**Comment by ArendAlphaEagle** [comment]
Sorry, I'm kinda a n00b at this. I just wanted to pull in a request and github wouldn't let me until I compared two branches.

**Comment by chrislo27** [comment]
You have to compare my master branch to your master branch. Resubmit this
pull request please.

**Pull request closed without merging**
